---
name: activejob
version: '6.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 04ed82d7df5d5ee825d7864abfa29d624b52e549
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
